# @format

version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - richmotiv-db:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  webfront:
    build:
      context: ./frontend
    depends_on:
      - api
    ports:
      - "8080:5000"

volumes:
  richmotiv-db:
